### ISSUE TITLE
Do you need blender to run this?

### ISSUE THREAD

**Issue by HeavyDevy1** [QuestionableM/SM-Converter#6]
do you need blender to run this, I"m really curious. I am not a genius when it comes to computers and all I want is to turn my blueprints from scrap mechanic into a file so I can 3d print it.

**Comment by HeavyDevy1** [comment]
How do I put the program into the software that supports the .obj file. And
what is some software that can run .obj files?

I am very new to this stuff, I am sorry for the inconvenience.

**Comment by QuestionableM** [comment]
As far the the program itself (SM-Converter) goes, you need to run the program, select the blueprint that you want to convert to 3D model and then press on the `Convert` button. When it's done you go to the `ConvertedBlueprints` (Which is located in the same folder as the `exe` file) folder and there you have the .obj file read to be used.

I'm not really a 3D printing guy, so I'm not really aware of what goes into that stuff, but as far as I know you need to convert the .obj model into the .stl model.

Here's a Reddit link I was able to find about getting started with 3D printing:
https://www.reddit.com/r/3Dprinting/wiki/makingmodels/

And here's a Reddit link that has some stuff regarding the OBJ to STL conversion:
https://www.reddit.com/r/3Dprinting/comments/3pwxa7/need_help_converting_a_obj_to_stl/

I hope this helps

**Comment by HeavyDevy1** [comment]
Thank you so much, I found out how to do it. Have a wonderful day!

**Comment by QuestionableM** [comment]
You're welcome.
